### ISSUE TITLE
Review 1

### ISSUE THREAD

**Issue by 10Dozen** [rempopo/CO24_Break_line.WL_Rosche#1]
### Mission:
 - [x] 1. Слоты:  отряды 1,3 и 1,4 вместо 1'3 1'4 (и в gear/Kits.sqf обновить)
 - [x] 2. Слоты: 1969 год, а автоматик рифлемены =\ M60 както жирно и тяжело, полагаю в каждый сквад. Вот тут http://grunt-redux.atspace.eu/us_marines_forces1.htm пишут что структура аналогична Вьетнаму -- М14/М16 + M203/М79 в райфл сквадах, М60 в вепон сквадах.
 - [x] 3. Маркер Destroed enemy convoy --> нужно Destro**y**ed
 - [x] 4. Артиллерия: У арты минимальная дистанция около 800 метров, нужно указать в заметках для зевса, что мол ближе 800 м можно стрелять _только_ прямой наводкой.
 - [x] 5. 

### tSF:
 - [ ] 1.  MissionCondition: Артиллерии 2 штуки, а условие только для ART1
 - [x] 2. Чем тебе POM не угодил? Никогда не включаешь - а полезный инструмент!
 - [x] 3. 

### Dynai:
 - [x] 1. Ругается на отсутствие зоны reinf1, в диагностике Дуная тоже ее нет. У тебя на карте стоит reinf1, а в конфиге дуная -- reinf. Нужно чтобы везде одинаково.
 - [ ] 2. В reinf для машины указано Vehicle Advance но не указаны кейпоинты. Подобное поведение работает следующим образом -- машина спавнится и на последнем вейпоинте выгружает пехоту и переходит в режим удержания. Так вот вейпоинты берутся откуда? Либо рандомно в зоне, либо из кейпоинтов. И тут смотрим что сделано у тебя -- кейпоинтов нет, а зона вне карты и очень маленькая. То есть машина появилась и уехала охранять дорогу вне карты.
Вместо этого тебе нужно сделать так:
а) Выбрать геймлоджик зоны
б) Ctrl+SPace -> [Dynai] Add Zone's Asset -> Keypoint
в) Расставить кейпоинты в области куда в конце концов нужно приехать и где воевать (например в первом квартале города)
г) Если хочешь чтобы машина спавнилась в конкретной точке -- то делаешь Ctrl+SPace -> [Dynai] Add Zone's Asset -> Vehicle Points -- тогда машинку заспавнит не рандомно в зоне, а на одной из этих точек
д) (опционально) из пункта (г) выходит, что можно сделать наоборот -- саму зону разместить на въезде в город, а потом добавить Vehicle Point за картой. Тогда при активации зоны машина заспавнится вне города на заданной vehicle point, а потом поедет на рандомные вейпоинты в зоне у города.

Затестить можешь через карту -- tS Admin Tools - Dynai tool -- там можно зону активировать в любой момент и в зевсе посмотреть как себя ведет.
 - [x] 3. 

### Gear:
 - [x] 1. Вынести М60 в отдельный вепон сквад и выдать станки (1+ 3 + 3 (фаертимы вида - фт лидер с патронами и бинклем, мг с пулеметом и патронами, ассистант мг с станком и патронами))

**Comment by Comrade333** [comment]
**Mission:**
 1. Переделал.
 2. Изменил структуры отделений.
 3. Исправил
 4. Указал в заметках.


**tSF:**
 1. Добавил в кондишены  про вторую гаубицу.
 2. Включил.

**Dynai:**
 1. Переименовал.
 2. Добавил кейпоинты.


**Gear:**
 1. Готово.

**Comment by 10Dozen** [comment]
**tSF:**
 1. Кондишены не полные. 
1-- в городе нет врагов и обе арты живы, 
2-- в городе нет врагов и обе арты мертвы, 
3 -- в городе много врагов и обе арты мертвы

Но если только 1 арт установка сломана, то ни одно из условий не будет выполнено.
Для первого кондишена сделай `(alive ART1 || alive ART2)` -- типа если хоть одна арта жива но город зачищен -- концовка 1.

 2. 

**Dynai:**
2. Плохо сделано. Я же говорю -- выбирается _случайно_ по кейпоинтам. А ты поставил кейпоинт за пределами карты. На что ты рассчитываешь? Что машина проедет по вейпоинтам и вернется за край карты? Еще раз:
**в) Расставить кейпоинты в области куда в конце концов нужно приехать и где воевать (например в первом квартале города)**

**Comment by 10Dozen** [comment]
Поправил в https://github.com/rempopo/CO24_Break_line.WL_Rosche/commit/ba92ae3af478f7099c0c65e0ad983f963f7aa3d8
